-- Project HANGAR — Phase 20.6, defect B46: the indexes the (date, id) keyset
-- pages actually need.
--
-- ── WHY AN INDEX MIGRATION BELONGS WITH B46 ──────────────────────────────
-- B46's visible half was a type error: an uncast row comparison made sqlc
-- generate `time.Time` for a bigint parameter, so five paginated endpoints
-- returned 500 on every call. Fixing the casts makes them execute. It does
-- not make them *ordered*, and that is the half of the defect that would
-- have survived the obvious fix.
--
-- A keyset page is only correct if the sort key is a TOTAL order. Each of
-- these four tables was indexed on (owner…, time DESC) and ordered by the
-- same, with the row id present in the PRIMARY KEY but absent from both the
-- index and the ORDER BY. Two rows sharing a timestamp were therefore
-- returned in whatever order the scan produced, which is free to differ
-- between two executions of the same query. Paginating over that loses rows
-- silently: the cursor names a row, the next page asks for "everything after
-- it", and if the tie re-orders in between, the rows that moved above the
-- cursor are never served. ESI makes this routine rather than theoretical —
-- wallet journal entries and notifications arrive in batches stamped to the
-- same second.
--
-- So the queries now order by (time DESC, id DESC) and these indexes match
-- that key exactly, DESC included. Matching matters: with the index on
-- (time DESC) only, Postgres can satisfy the filter from the index but must
-- then sort to resolve the tiebreak, which reintroduces a full sort of the
-- matched set on every page. With the id in the index, the row comparison
-- becomes an Index Cond rather than a post-filter and the ORDER BY is
-- satisfied by the scan order itself — no Sort node at all.
--
-- Measured on the live installation at the time of writing (EXPLAIN with
-- enable_seqscan=off, which is needed only because app.wallet_journal holds
-- 7 rows there and a seq scan genuinely is cheaper at that size):
--
--   Limit
--     ->  Index Scan using wallet_journal_default_owner_kind_owner_id_division_date_jo_idx
--           Index Cond: ((owner_kind = ...) AND (owner_id = ...) AND
--                        (division = ...) AND (ROW(date, journal_id) < ROW(...)))
--
-- The whole predicate is an Index Cond and there is no Sort. On a real
-- wallet the planner reaches that plan on its own.
--
-- ── `division` IS IN THE WALLET KEYS AND WAS IN NO INDEX ─────────────────
-- Both wallet queries have filtered on `division` since Phase 8, and neither
-- index contained it. A corporation has up to 7 divisions in one table, so
-- reading division 3's newest 50 rows meant scanning all divisions' rows in
-- date order and discarding ~6/7 of them. It is in the leading equality
-- group here, where it belongs.
--
-- ── THE OLD INDEXES ARE DROPPED, NOT KEPT ────────────────────────────────
-- Each new index has the old one's columns as a strict prefix, so the old
-- index can serve no query the new one cannot. Keeping both would cost a
-- second write on every insert to buy nothing. The BRIN indexes on the time
-- columns are NOT touched: they serve partition-wide range scans (the
-- retention sweeps), which is a different access pattern from these pages.
--
-- Index names were server-generated by the original `CREATE INDEX ON <table>
-- (...)` form, so they are spelled out here rather than guessed.

-- +goose Up

-- #1 — app.wallet_journal: (owner_kind, owner_id, division) equality, then
-- the (date, journal_id) keyset. Created on the partitioned parent so it
-- propagates to every partition, present and future (the 00014 convention).
DROP INDEX IF EXISTS app.wallet_journal_owner_kind_owner_id_date_idx;
CREATE INDEX wallet_journal_keyset_idx
    ON app.wallet_journal (owner_kind, owner_id, division, date DESC, journal_id DESC);

-- #2 — app.wallet_transaction: same shape, transaction_id as the tiebreak.
DROP INDEX IF EXISTS app.wallet_transaction_owner_kind_owner_id_date_idx;
CREATE INDEX wallet_transaction_keyset_idx
    ON app.wallet_transaction (owner_kind, owner_id, division, date DESC, transaction_id DESC);

-- #3 — app.mail_header: character equality, then the (sent_at, mail_id)
-- keyset. Not partitioned, so this is a plain index.
DROP INDEX IF EXISTS app.mail_header_character_id_sent_at_idx;
CREATE INDEX mail_header_keyset_idx
    ON app.mail_header (character_id, sent_at DESC, mail_id DESC);

-- #4 — app.character_notification: character equality, then the
-- (sent_at, notification_id) keyset.
DROP INDEX IF EXISTS app.character_notification_character_id_sent_at_idx;
CREATE INDEX character_notification_keyset_idx
    ON app.character_notification (character_id, sent_at DESC, notification_id DESC);

-- +goose Down
DROP INDEX IF EXISTS app.character_notification_keyset_idx;
CREATE INDEX character_notification_character_id_sent_at_idx
    ON app.character_notification (character_id, sent_at DESC);

DROP INDEX IF EXISTS app.mail_header_keyset_idx;
CREATE INDEX mail_header_character_id_sent_at_idx
    ON app.mail_header (character_id, sent_at DESC);

DROP INDEX IF EXISTS app.wallet_transaction_keyset_idx;
CREATE INDEX wallet_transaction_owner_kind_owner_id_date_idx
    ON app.wallet_transaction (owner_kind, owner_id, date DESC);

DROP INDEX IF EXISTS app.wallet_journal_keyset_idx;
CREATE INDEX wallet_journal_owner_kind_owner_id_date_idx
    ON app.wallet_journal (owner_kind, owner_id, date DESC);
