// Phase 13's own minimal reconstruction of the subset of Mumble's
// MurmurRPC gRPC interface (github.com/mumble-voip/mumble,
// src/murmur/MurmurRPC.proto) that internal/provisioning/drivers/mumble
// needs: root-channel discovery (TreeQuery), ACL group membership
// read-modify-write (ACLQuery/ACLSet), and the bidirectional
// external-authenticator stream (Authenticate).
//
// IMPORTANT CAVEAT, reported per this phase's own instruction to surface
// spec/upstream uncertainty rather than silently guess: this file was
// authored from general knowledge of MurmurRPC's documented shape, NOT
// vendored or copied from Mumble's own source (avoiding reproducing
// upstream source verbatim). Real MurmurRPC.proto's exact field NUMBERS
// must match on the wire for a real Murmur server to understand this
// client — protobuf field numbers are the wire-format identity, not the
// field names. Before pointing this driver at a real Murmur server, an
// operator/integrator should diff this file against the target Murmur
// version's actual MurmurRPC.proto (shipped in Murmur's own source tree)
// and correct any field-number mismatch. grpc.go's own doc comment
// repeats this caveat at the call site.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: murmurrpc.proto

package murmurrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	V1_TreeQuery_FullMethodName    = "/murmurrpc.V1/TreeQuery"
	V1_ACLQuery_FullMethodName     = "/murmurrpc.V1/ACLQuery"
	V1_ACLSet_FullMethodName       = "/murmurrpc.V1/ACLSet"
	V1_Authenticate_FullMethodName = "/murmurrpc.V1/Authenticate"
)

// V1Client is the client API for V1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// V1 is the gRPC service surface this driver calls.
type V1Client interface {
	TreeQuery(ctx context.Context, in *Server, opts ...grpc.CallOption) (*Tree, error)
	ACLQuery(ctx context.Context, in *Channel, opts ...grpc.CallOption) (*ACL, error)
	ACLSet(ctx context.Context, in *ACL, opts ...grpc.CallOption) (*Void, error)
	Authenticate(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Authenticator_Response, Authenticator_Request], error)
}

type v1Client struct {
	cc grpc.ClientConnInterface
}

func NewV1Client(cc grpc.ClientConnInterface) V1Client {
	return &v1Client{cc}
}

func (c *v1Client) TreeQuery(ctx context.Context, in *Server, opts ...grpc.CallOption) (*Tree, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tree)
	err := c.cc.Invoke(ctx, V1_TreeQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *v1Client) ACLQuery(ctx context.Context, in *Channel, opts ...grpc.CallOption) (*ACL, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ACL)
	err := c.cc.Invoke(ctx, V1_ACLQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *v1Client) ACLSet(ctx context.Context, in *ACL, opts ...grpc.CallOption) (*Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Void)
	err := c.cc.Invoke(ctx, V1_ACLSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *v1Client) Authenticate(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Authenticator_Response, Authenticator_Request], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &V1_ServiceDesc.Streams[0], V1_Authenticate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Authenticator_Response, Authenticator_Request]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type V1_AuthenticateClient = grpc.BidiStreamingClient[Authenticator_Response, Authenticator_Request]

// V1Server is the server API for V1 service.
// All implementations must embed UnimplementedV1Server
// for forward compatibility.
//
// V1 is the gRPC service surface this driver calls.
type V1Server interface {
	TreeQuery(context.Context, *Server) (*Tree, error)
	ACLQuery(context.Context, *Channel) (*ACL, error)
	ACLSet(context.Context, *ACL) (*Void, error)
	Authenticate(grpc.BidiStreamingServer[Authenticator_Response, Authenticator_Request]) error
	mustEmbedUnimplementedV1Server()
}

// UnimplementedV1Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedV1Server struct{}

func (UnimplementedV1Server) TreeQuery(context.Context, *Server) (*Tree, error) {
	return nil, status.Error(codes.Unimplemented, "method TreeQuery not implemented")
}
func (UnimplementedV1Server) ACLQuery(context.Context, *Channel) (*ACL, error) {
	return nil, status.Error(codes.Unimplemented, "method ACLQuery not implemented")
}
func (UnimplementedV1Server) ACLSet(context.Context, *ACL) (*Void, error) {
	return nil, status.Error(codes.Unimplemented, "method ACLSet not implemented")
}
func (UnimplementedV1Server) Authenticate(grpc.BidiStreamingServer[Authenticator_Response, Authenticator_Request]) error {
	return status.Error(codes.Unimplemented, "method Authenticate not implemented")
}
func (UnimplementedV1Server) mustEmbedUnimplementedV1Server() {}
func (UnimplementedV1Server) testEmbeddedByValue()            {}

// UnsafeV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to V1Server will
// result in compilation errors.
type UnsafeV1Server interface {
	mustEmbedUnimplementedV1Server()
}

func RegisterV1Server(s grpc.ServiceRegistrar, srv V1Server) {
	// If the following call panics, it indicates UnimplementedV1Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&V1_ServiceDesc, srv)
}

func _V1_TreeQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Server)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(V1Server).TreeQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: V1_TreeQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(V1Server).TreeQuery(ctx, req.(*Server))
	}
	return interceptor(ctx, in, info, handler)
}

func _V1_ACLQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Channel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(V1Server).ACLQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: V1_ACLQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(V1Server).ACLQuery(ctx, req.(*Channel))
	}
	return interceptor(ctx, in, info, handler)
}

func _V1_ACLSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ACL)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(V1Server).ACLSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: V1_ACLSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(V1Server).ACLSet(ctx, req.(*ACL))
	}
	return interceptor(ctx, in, info, handler)
}

func _V1_Authenticate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(V1Server).Authenticate(&grpc.GenericServerStream[Authenticator_Response, Authenticator_Request]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type V1_AuthenticateServer = grpc.BidiStreamingServer[Authenticator_Response, Authenticator_Request]

// V1_ServiceDesc is the grpc.ServiceDesc for V1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var V1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "murmurrpc.V1",
	HandlerType: (*V1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TreeQuery",
			Handler:    _V1_TreeQuery_Handler,
		},
		{
			MethodName: "ACLQuery",
			Handler:    _V1_ACLQuery_Handler,
		},
		{
			MethodName: "ACLSet",
			Handler:    _V1_ACLSet_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Authenticate",
			Handler:       _V1_Authenticate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "murmurrpc.proto",
}
