// Phase 13's own minimal reconstruction of the subset of Mumble's
// MurmurRPC gRPC interface (github.com/mumble-voip/mumble,
// src/murmur/MurmurRPC.proto) that internal/provisioning/drivers/mumble
// needs: root-channel discovery (TreeQuery), ACL group membership
// read-modify-write (ACLQuery/ACLSet), and the bidirectional
// external-authenticator stream (Authenticate).
//
// IMPORTANT CAVEAT, reported per this phase's own instruction to surface
// spec/upstream uncertainty rather than silently guess: this file was
// authored from general knowledge of MurmurRPC's documented shape, NOT
// vendored or copied from Mumble's own source (avoiding reproducing
// upstream source verbatim). Real MurmurRPC.proto's exact field NUMBERS
// must match on the wire for a real Murmur server to understand this
// client — protobuf field numbers are the wire-format identity, not the
// field names. Before pointing this driver at a real Murmur server, an
// operator/integrator should diff this file against the target Murmur
// version's actual MurmurRPC.proto (shipped in Murmur's own source tree)
// and correct any field-number mismatch. grpc.go's own doc comment
// repeats this caveat at the call site.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: murmurrpc.proto

package murmurrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Authenticator_Response_Status int32

const (
	Authenticator_Response_STATUS_UNKNOWN   Authenticator_Response_Status = 0
	Authenticator_Response_STATUS_OK        Authenticator_Response_Status = 1
	Authenticator_Response_STATUS_FAIL      Authenticator_Response_Status = 2
	Authenticator_Response_STATUS_TEMPORARY Authenticator_Response_Status = 3
)

// Enum value maps for Authenticator_Response_Status.
var (
	Authenticator_Response_Status_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_OK",
		2: "STATUS_FAIL",
		3: "STATUS_TEMPORARY",
	}
	Authenticator_Response_Status_value = map[string]int32{
		"STATUS_UNKNOWN":   0,
		"STATUS_OK":        1,
		"STATUS_FAIL":      2,
		"STATUS_TEMPORARY": 3,
	}
)

func (x Authenticator_Response_Status) Enum() *Authenticator_Response_Status {
	p := new(Authenticator_Response_Status)
	*p = x
	return p
}

func (x Authenticator_Response_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Authenticator_Response_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_murmurrpc_proto_enumTypes[0].Descriptor()
}

func (Authenticator_Response_Status) Type() protoreflect.EnumType {
	return &file_murmurrpc_proto_enumTypes[0]
}

func (x Authenticator_Response_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Authenticator_Response_Status.Descriptor instead.
func (Authenticator_Response_Status) EnumDescriptor() ([]byte, []int) {
	return file_murmurrpc_proto_rawDescGZIP(), []int{6, 1, 0}
}

type Void struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Void) Reset() {
	*x = Void{}
	mi := &file_murmurrpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Void) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Void) ProtoMessage() {}

func (x *Void) ProtoReflect() protoreflect.Message {
	mi := &file_murmurrpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Void.ProtoReflect.Descriptor instead.
func (*Void) Descriptor() ([]byte, []int) {
	return file_murmurrpc_proto_rawDescGZIP(), []int{0}
}

// Server identifies one Murmur virtual server by its configured id
// (HANGAR_MUMBLE_SERVER_ID).
type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_murmurrpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_murmurrpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_murmurrpc_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Channel identifies one channel on one server. parent is set on requests
// that need to disambiguate by hierarchy; responses always carry id.
type Channel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Id            uint32                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Channel) Reset() {
	*x = Channel{}
	mi := &file_murmurrpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Channel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Channel) ProtoMessage() {}

func (x *Channel) ProtoReflect() protoreflect.Message {
	mi := &file_murmurrpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Channel.ProtoReflect.Descriptor instead.
func (*Channel) Descriptor() ([]byte, []int) {
	return file_murmurrpc_proto_rawDescGZIP(), []int{2}
}

func (x *Channel) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Channel) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Channel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// User is a currently-connected session — NOT a registered account.
// ACL group membership is keyed on the registered user id (ACL.Group's
// add/remove lists below), which is a distinct namespace from a
// connected session's ephemeral id.
type MumbleUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Session       uint32                 `protobuf:"varint,2,opt,name=session,proto3" json:"session,omitempty"`
	UserId        uint32                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MumbleUser) Reset() {
	*x = MumbleUser{}
	mi := &file_murmurrpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MumbleUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MumbleUser) ProtoMessage() {}

func (x *MumbleUser) ProtoReflect() protoreflect.Message {
	mi := &file_murmurrpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MumbleUser.ProtoReflect.Descriptor instead.
func (*MumbleUser) Descriptor() ([]byte, []int) {
	return file_murmurrpc_proto_rawDescGZIP(), []int{3}
}

func (x *MumbleUser) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *MumbleUser) GetSession() uint32 {
	if x != nil {
		return x.Session
	}
	return 0
}

func (x *MumbleUser) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MumbleUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Tree is the recursive channel/user hierarchy TreeQuery returns —
// HANGAR only ever reads Tree.channel.id at the root to discover the
// configured server's root channel id when no explicit channel is
// configured (01_ARCHITECTURE.md §9.5 / roadmap: "HANGAR manages the root
// channel unless configured otherwise").
type Tree struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       *Channel               `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Children      []*Tree                `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
	Users         []*MumbleUser          `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tree) Reset() {
	*x = Tree{}
	mi := &file_murmurrpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tree) ProtoMessage() {}

func (x *Tree) ProtoReflect() protoreflect.Message {
	mi := &file_murmurrpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tree.ProtoReflect.Descriptor instead.
func (*Tree) Descriptor() ([]byte, []int) {
	return file_murmurrpc_proto_rawDescGZIP(), []int{4}
}

func (x *Tree) GetChannel() *Channel {
	if x != nil {
		return x.Channel
	}
	return nil
}

func (x *Tree) GetChildren() []*Tree {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *Tree) GetUsers() []*MumbleUser {
	if x != nil {
		return x.Users
	}
	return nil
}

// ACL is one channel's full access-control configuration. Group
// membership is force-add/force-remove: Group.add and Group.remove are
// explicit registered-user-id lists that override the group's natural
// membership rule for exactly those users — this is what "ACL group
// add/remove" (roadmap) actually modifies. Mumble has no single-member
// add/remove RPC: the whole Group list is read via ACLQuery, one Group's
// add/remove lists are edited in place, and the WHOLE ACL is written back
// via ACLSet — acl.go's read-modify-write pattern exists because this is
// the only mechanism Murmur exposes.
type ACL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       *Channel               `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Acls          []*ACL_Entry           `protobuf:"bytes,2,rep,name=acls,proto3" json:"acls,omitempty"`
	Groups        []*ACL_Group           `protobuf:"bytes,3,rep,name=groups,proto3" json:"groups,omitempty"`
	Inherit       bool                   `protobuf:"varint,4,opt,name=inherit,proto3" json:"inherit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ACL) Reset() {
	*x = ACL{}
	mi := &file_murmurrpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ACL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACL) ProtoMessage() {}

func (x *ACL) ProtoReflect() protoreflect.Message {
	mi := &file_murmurrpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACL.ProtoReflect.Descriptor instead.
func (*ACL) Descriptor() ([]byte, []int) {
	return file_murmurrpc_proto_rawDescGZIP(), []int{5}
}

func (x *ACL) GetChannel() *Channel {
	if x != nil {
		return x.Channel
	}
	return nil
}

func (x *ACL) GetAcls() []*ACL_Entry {
	if x != nil {
		return x.Acls
	}
	return nil
}

func (x *ACL) GetGroups() []*ACL_Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *ACL) GetInherit() bool {
	if x != nil {
		return x.Inherit
	}
	return false
}

// Authenticator is the external-authenticator bidirectional stream
// (01_ARCHITECTURE.md §9.5: "the only mechanism that achieves absolute
// denial rather than group removal"). HANGAR dials Murmur and calls V1's
// Authenticate RPC as the gRPC CLIENT, but Murmur is logically the one
// asking questions: Murmur (the gRPC server for this call) pushes one
// Request per connecting client down the SERVER->CLIENT direction, and
// HANGAR answers each over the CLIENT->SERVER direction — the RPC
// signature below is deliberately "backwards" from a naive
// request-then-response reading (V1.Authenticate's client stream carries
// Response messages, its server stream carries Request messages) to
// match that real interaction shape. Status.STATUS_FAIL denies the
// connection outright, never merely removing a group.
type Authenticator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Authenticator) Reset() {
	*x = Authenticator{}
	mi := &file_murmurrpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authenticator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authenticator) ProtoMessage() {}

func (x *Authenticator) ProtoReflect() protoreflect.Message {
	mi := &file_murmurrpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authenticator.ProtoReflect.Descriptor instead.
func (*Authenticator) Descriptor() ([]byte, []int) {
	return file_murmurrpc_proto_rawDescGZIP(), []int{6}
}

type ACL_Group struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Inherited        bool                   `protobuf:"varint,2,opt,name=inherited,proto3" json:"inherited,omitempty"`
	Inherit          bool                   `protobuf:"varint,3,opt,name=inherit,proto3" json:"inherit,omitempty"`
	Inheritable      bool                   `protobuf:"varint,4,opt,name=inheritable,proto3" json:"inheritable,omitempty"`
	Add              []uint32               `protobuf:"varint,5,rep,packed,name=add,proto3" json:"add,omitempty"`
	Remove           []uint32               `protobuf:"varint,6,rep,packed,name=remove,proto3" json:"remove,omitempty"`
	InheritedMembers []uint32               `protobuf:"varint,7,rep,packed,name=inherited_members,json=inheritedMembers,proto3" json:"inherited_members,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ACL_Group) Reset() {
	*x = ACL_Group{}
	mi := &file_murmurrpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ACL_Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACL_Group) ProtoMessage() {}

func (x *ACL_Group) ProtoReflect() protoreflect.Message {
	mi := &file_murmurrpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACL_Group.ProtoReflect.Descriptor instead.
func (*ACL_Group) Descriptor() ([]byte, []int) {
	return file_murmurrpc_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ACL_Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ACL_Group) GetInherited() bool {
	if x != nil {
		return x.Inherited
	}
	return false
}

func (x *ACL_Group) GetInherit() bool {
	if x != nil {
		return x.Inherit
	}
	return false
}

func (x *ACL_Group) GetInheritable() bool {
	if x != nil {
		return x.Inheritable
	}
	return false
}

func (x *ACL_Group) GetAdd() []uint32 {
	if x != nil {
		return x.Add
	}
	return nil
}

func (x *ACL_Group) GetRemove() []uint32 {
	if x != nil {
		return x.Remove
	}
	return nil
}

func (x *ACL_Group) GetInheritedMembers() []uint32 {
	if x != nil {
		return x.InheritedMembers
	}
	return nil
}

type ACL_Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       *Channel               `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	ApplyHere     bool                   `protobuf:"varint,2,opt,name=apply_here,json=applyHere,proto3" json:"apply_here,omitempty"`
	ApplySubs     bool                   `protobuf:"varint,3,opt,name=apply_subs,json=applySubs,proto3" json:"apply_subs,omitempty"`
	Inherited     bool                   `protobuf:"varint,4,opt,name=inherited,proto3" json:"inherited,omitempty"`
	UserId        uint32                 `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Group         string                 `protobuf:"bytes,6,opt,name=group,proto3" json:"group,omitempty"`
	Allow         int32                  `protobuf:"varint,7,opt,name=allow,proto3" json:"allow,omitempty"`
	Deny          int32                  `protobuf:"varint,8,opt,name=deny,proto3" json:"deny,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ACL_Entry) Reset() {
	*x = ACL_Entry{}
	mi := &file_murmurrpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ACL_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ACL_Entry) ProtoMessage() {}

func (x *ACL_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_murmurrpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ACL_Entry.ProtoReflect.Descriptor instead.
func (*ACL_Entry) Descriptor() ([]byte, []int) {
	return file_murmurrpc_proto_rawDescGZIP(), []int{5, 1}
}

func (x *ACL_Entry) GetChannel() *Channel {
	if x != nil {
		return x.Channel
	}
	return nil
}

func (x *ACL_Entry) GetApplyHere() bool {
	if x != nil {
		return x.ApplyHere
	}
	return false
}

func (x *ACL_Entry) GetApplySubs() bool {
	if x != nil {
		return x.ApplySubs
	}
	return false
}

func (x *ACL_Entry) GetInherited() bool {
	if x != nil {
		return x.Inherited
	}
	return false
}

func (x *ACL_Entry) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ACL_Entry) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ACL_Entry) GetAllow() int32 {
	if x != nil {
		return x.Allow
	}
	return 0
}

func (x *ACL_Entry) GetDeny() int32 {
	if x != nil {
		return x.Deny
	}
	return 0
}

type Authenticator_Request struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Initialize    *Authenticator_Request_Initialize   `protobuf:"bytes,1,opt,name=initialize,proto3" json:"initialize,omitempty"`
	Authenticate  *Authenticator_Request_Authenticate `protobuf:"bytes,2,opt,name=authenticate,proto3" json:"authenticate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Authenticator_Request) Reset() {
	*x = Authenticator_Request{}
	mi := &file_murmurrpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authenticator_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authenticator_Request) ProtoMessage() {}

func (x *Authenticator_Request) ProtoReflect() protoreflect.Message {
	mi := &file_murmurrpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authenticator_Request.ProtoReflect.Descriptor instead.
func (*Authenticator_Request) Descriptor() ([]byte, []int) {
	return file_murmurrpc_proto_rawDescGZIP(), []int{6, 0}
}

func (x *Authenticator_Request) GetInitialize() *Authenticator_Request_Initialize {
	if x != nil {
		return x.Initialize
	}
	return nil
}

func (x *Authenticator_Request) GetAuthenticate() *Authenticator_Request_Authenticate {
	if x != nil {
		return x.Authenticate
	}
	return nil
}

type Authenticator_Response struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Status        Authenticator_Response_Status `protobuf:"varint,1,opt,name=status,proto3,enum=murmurrpc.Authenticator_Response_Status" json:"status,omitempty"`
	UserId        int32                         `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                        `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Authenticator_Response) Reset() {
	*x = Authenticator_Response{}
	mi := &file_murmurrpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authenticator_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authenticator_Response) ProtoMessage() {}

func (x *Authenticator_Response) ProtoReflect() protoreflect.Message {
	mi := &file_murmurrpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authenticator_Response.ProtoReflect.Descriptor instead.
func (*Authenticator_Response) Descriptor() ([]byte, []int) {
	return file_murmurrpc_proto_rawDescGZIP(), []int{6, 1}
}

func (x *Authenticator_Response) GetStatus() Authenticator_Response_Status {
	if x != nil {
		return x.Status
	}
	return Authenticator_Response_STATUS_UNKNOWN
}

func (x *Authenticator_Response) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Authenticator_Response) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Authenticator_Request_Initialize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uptime        uint32                 `protobuf:"varint,1,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Authenticator_Request_Initialize) Reset() {
	*x = Authenticator_Request_Initialize{}
	mi := &file_murmurrpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authenticator_Request_Initialize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authenticator_Request_Initialize) ProtoMessage() {}

func (x *Authenticator_Request_Initialize) ProtoReflect() protoreflect.Message {
	mi := &file_murmurrpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authenticator_Request_Initialize.ProtoReflect.Descriptor instead.
func (*Authenticator_Request_Initialize) Descriptor() ([]byte, []int) {
	return file_murmurrpc_proto_rawDescGZIP(), []int{6, 0, 0}
}

func (x *Authenticator_Request_Initialize) GetUptime() uint32 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

type Authenticator_Request_Authenticate struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password          string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Certificates      [][]byte               `protobuf:"bytes,3,rep,name=certificates,proto3" json:"certificates,omitempty"`
	CertificateHash   string                 `protobuf:"bytes,4,opt,name=certificate_hash,json=certificateHash,proto3" json:"certificate_hash,omitempty"`
	StrongCertificate bool                   `protobuf:"varint,5,opt,name=strong_certificate,json=strongCertificate,proto3" json:"strong_certificate,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Authenticator_Request_Authenticate) Reset() {
	*x = Authenticator_Request_Authenticate{}
	mi := &file_murmurrpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authenticator_Request_Authenticate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authenticator_Request_Authenticate) ProtoMessage() {}

func (x *Authenticator_Request_Authenticate) ProtoReflect() protoreflect.Message {
	mi := &file_murmurrpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authenticator_Request_Authenticate.ProtoReflect.Descriptor instead.
func (*Authenticator_Request_Authenticate) Descriptor() ([]byte, []int) {
	return file_murmurrpc_proto_rawDescGZIP(), []int{6, 0, 1}
}

func (x *Authenticator_Request_Authenticate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Authenticator_Request_Authenticate) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Authenticator_Request_Authenticate) GetCertificates() [][]byte {
	if x != nil {
		return x.Certificates
	}
	return nil
}

func (x *Authenticator_Request_Authenticate) GetCertificateHash() string {
	if x != nil {
		return x.CertificateHash
	}
	return ""
}

func (x *Authenticator_Request_Authenticate) GetStrongCertificate() bool {
	if x != nil {
		return x.StrongCertificate
	}
	return false
}

var File_murmurrpc_proto protoreflect.FileDescriptor

const file_murmurrpc_proto_rawDesc = "" +
	"\n" +
	"\x0fmurmurrpc.proto\x12\tmurmurrpc\"\x06\n" +
	"\x04Void\"\x18\n" +
	"\x06Server\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"X\n" +
	"\aChannel\x12)\n" +
	"\x06server\x18\x01 \x01(\v2\x11.murmurrpc.ServerR\x06server\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"~\n" +
	"\n" +
	"MumbleUser\x12)\n" +
	"\x06server\x18\x01 \x01(\v2\x11.murmurrpc.ServerR\x06server\x12\x18\n" +
	"\asession\x18\x02 \x01(\rR\asession\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\rR\x06userId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"\x8e\x01\n" +
	"\x04Tree\x12,\n" +
	"\achannel\x18\x01 \x01(\v2\x12.murmurrpc.ChannelR\achannel\x12+\n" +
	"\bchildren\x18\x02 \x03(\v2\x0f.murmurrpc.TreeR\bchildren\x12+\n" +
	"\x05users\x18\x03 \x03(\v2\x15.murmurrpc.MumbleUserR\x05users\"\xe1\x04\n" +
	"\x03ACL\x12,\n" +
	"\achannel\x18\x01 \x01(\v2\x12.murmurrpc.ChannelR\achannel\x12(\n" +
	"\x04acls\x18\x02 \x03(\v2\x14.murmurrpc.ACL.EntryR\x04acls\x12,\n" +
	"\x06groups\x18\x03 \x03(\v2\x14.murmurrpc.ACL.GroupR\x06groups\x12\x18\n" +
	"\ainherit\x18\x04 \x01(\bR\ainherit\x1a\xcc\x01\n" +
	"\x05Group\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tinherited\x18\x02 \x01(\bR\tinherited\x12\x18\n" +
	"\ainherit\x18\x03 \x01(\bR\ainherit\x12 \n" +
	"\vinheritable\x18\x04 \x01(\bR\vinheritable\x12\x10\n" +
	"\x03add\x18\x05 \x03(\rR\x03add\x12\x16\n" +
	"\x06remove\x18\x06 \x03(\rR\x06remove\x12+\n" +
	"\x11inherited_members\x18\a \x03(\rR\x10inheritedMembers\x1a\xea\x01\n" +
	"\x05Entry\x12,\n" +
	"\achannel\x18\x01 \x01(\v2\x12.murmurrpc.ChannelR\achannel\x12\x1d\n" +
	"\n" +
	"apply_here\x18\x02 \x01(\bR\tapplyHere\x12\x1d\n" +
	"\n" +
	"apply_subs\x18\x03 \x01(\bR\tapplySubs\x12\x1c\n" +
	"\tinherited\x18\x04 \x01(\bR\tinherited\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\rR\x06userId\x12\x14\n" +
	"\x05group\x18\x06 \x01(\tR\x05group\x12\x14\n" +
	"\x05allow\x18\a \x01(\x05R\x05allow\x12\x12\n" +
	"\x04deny\x18\b \x01(\x05R\x04deny\"\xf0\x04\n" +
	"\rAuthenticator\x1a\x8e\x03\n" +
	"\aRequest\x12K\n" +
	"\n" +
	"initialize\x18\x01 \x01(\v2+.murmurrpc.Authenticator.Request.InitializeR\n" +
	"initialize\x12Q\n" +
	"\fauthenticate\x18\x02 \x01(\v2-.murmurrpc.Authenticator.Request.AuthenticateR\fauthenticate\x1a$\n" +
	"\n" +
	"Initialize\x12\x16\n" +
	"\x06uptime\x18\x01 \x01(\rR\x06uptime\x1a\xbc\x01\n" +
	"\fAuthenticate\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\"\n" +
	"\fcertificates\x18\x03 \x03(\fR\fcertificates\x12)\n" +
	"\x10certificate_hash\x18\x04 \x01(\tR\x0fcertificateHash\x12-\n" +
	"\x12strong_certificate\x18\x05 \x01(\bR\x11strongCertificate\x1a\xcd\x01\n" +
	"\bResponse\x12@\n" +
	"\x06status\x18\x01 \x01(\x0e2(.murmurrpc.Authenticator.Response.StatusR\x06status\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"R\n" +
	"\x06Status\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\r\n" +
	"\tSTATUS_OK\x10\x01\x12\x0f\n" +
	"\vSTATUS_FAIL\x10\x02\x12\x14\n" +
	"\x10STATUS_TEMPORARY\x10\x032\xe9\x01\n" +
	"\x02V1\x12/\n" +
	"\tTreeQuery\x12\x11.murmurrpc.Server\x1a\x0f.murmurrpc.Tree\x12.\n" +
	"\bACLQuery\x12\x12.murmurrpc.Channel\x1a\x0e.murmurrpc.ACL\x12)\n" +
	"\x06ACLSet\x12\x0e.murmurrpc.ACL\x1a\x0f.murmurrpc.Void\x12W\n" +
	"\fAuthenticate\x12!.murmurrpc.Authenticator.Response\x1a .murmurrpc.Authenticator.Request(\x010\x01BQZOgithub.com/hangar-project/hangar/internal/provisioning/drivers/mumble/murmurrpcb\x06proto3"

var (
	file_murmurrpc_proto_rawDescOnce sync.Once
	file_murmurrpc_proto_rawDescData []byte
)

func file_murmurrpc_proto_rawDescGZIP() []byte {
	file_murmurrpc_proto_rawDescOnce.Do(func() {
		file_murmurrpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_murmurrpc_proto_rawDesc), len(file_murmurrpc_proto_rawDesc)))
	})
	return file_murmurrpc_proto_rawDescData
}

var file_murmurrpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_murmurrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_murmurrpc_proto_goTypes = []any{
	(Authenticator_Response_Status)(0),         // 0: murmurrpc.Authenticator.Response.Status
	(*Void)(nil),                               // 1: murmurrpc.Void
	(*Server)(nil),                             // 2: murmurrpc.Server
	(*Channel)(nil),                            // 3: murmurrpc.Channel
	(*MumbleUser)(nil),                         // 4: murmurrpc.MumbleUser
	(*Tree)(nil),                               // 5: murmurrpc.Tree
	(*ACL)(nil),                                // 6: murmurrpc.ACL
	(*Authenticator)(nil),                      // 7: murmurrpc.Authenticator
	(*ACL_Group)(nil),                          // 8: murmurrpc.ACL.Group
	(*ACL_Entry)(nil),                          // 9: murmurrpc.ACL.Entry
	(*Authenticator_Request)(nil),              // 10: murmurrpc.Authenticator.Request
	(*Authenticator_Response)(nil),             // 11: murmurrpc.Authenticator.Response
	(*Authenticator_Request_Initialize)(nil),   // 12: murmurrpc.Authenticator.Request.Initialize
	(*Authenticator_Request_Authenticate)(nil), // 13: murmurrpc.Authenticator.Request.Authenticate
}
var file_murmurrpc_proto_depIdxs = []int32{
	2,  // 0: murmurrpc.Channel.server:type_name -> murmurrpc.Server
	2,  // 1: murmurrpc.MumbleUser.server:type_name -> murmurrpc.Server
	3,  // 2: murmurrpc.Tree.channel:type_name -> murmurrpc.Channel
	5,  // 3: murmurrpc.Tree.children:type_name -> murmurrpc.Tree
	4,  // 4: murmurrpc.Tree.users:type_name -> murmurrpc.MumbleUser
	3,  // 5: murmurrpc.ACL.channel:type_name -> murmurrpc.Channel
	9,  // 6: murmurrpc.ACL.acls:type_name -> murmurrpc.ACL.Entry
	8,  // 7: murmurrpc.ACL.groups:type_name -> murmurrpc.ACL.Group
	3,  // 8: murmurrpc.ACL.Entry.channel:type_name -> murmurrpc.Channel
	12, // 9: murmurrpc.Authenticator.Request.initialize:type_name -> murmurrpc.Authenticator.Request.Initialize
	13, // 10: murmurrpc.Authenticator.Request.authenticate:type_name -> murmurrpc.Authenticator.Request.Authenticate
	0,  // 11: murmurrpc.Authenticator.Response.status:type_name -> murmurrpc.Authenticator.Response.Status
	2,  // 12: murmurrpc.V1.TreeQuery:input_type -> murmurrpc.Server
	3,  // 13: murmurrpc.V1.ACLQuery:input_type -> murmurrpc.Channel
	6,  // 14: murmurrpc.V1.ACLSet:input_type -> murmurrpc.ACL
	11, // 15: murmurrpc.V1.Authenticate:input_type -> murmurrpc.Authenticator.Response
	5,  // 16: murmurrpc.V1.TreeQuery:output_type -> murmurrpc.Tree
	6,  // 17: murmurrpc.V1.ACLQuery:output_type -> murmurrpc.ACL
	1,  // 18: murmurrpc.V1.ACLSet:output_type -> murmurrpc.Void
	10, // 19: murmurrpc.V1.Authenticate:output_type -> murmurrpc.Authenticator.Request
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_murmurrpc_proto_init() }
func file_murmurrpc_proto_init() {
	if File_murmurrpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_murmurrpc_proto_rawDesc), len(file_murmurrpc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_murmurrpc_proto_goTypes,
		DependencyIndexes: file_murmurrpc_proto_depIdxs,
		EnumInfos:         file_murmurrpc_proto_enumTypes,
		MessageInfos:      file_murmurrpc_proto_msgTypes,
	}.Build()
	File_murmurrpc_proto = out.File
	file_murmurrpc_proto_goTypes = nil
	file_murmurrpc_proto_depIdxs = nil
}
