package domain

import (
	"fmt"
	"time"

	"github.com/google/uuid"
)

// CorporationProject mirrors app.corporation_project — the Principle 13 /
// Gate 6 fixture proving a `uuid` identifier issued by CCP coexists with
// `bigint` identifiers in the same schema without coercion in either
// direction (02_DATABASE_SCHEMA.md §5.3). ProjectID is NEVER generated by
// HANGAR: it arrives from ESI as `type: string, format: uuid` and is stored
// exactly as received.
type CorporationProject struct {
	ProjectID        uuid.UUID // FROM CCP — never uuidv7()-generated here
	CorporationID    int64     // bigint, alongside the uuid PK, in the same row
	Name             string
	State            string // open vocabulary
	ContributionType *string
	TargetProgress   *Money
	CurrentProgress  *Money
	RewardISK        *Money
	ExpiresAt        *time.Time
}

// Validate enforces the Gate 6 invariant: ProjectID must be a real,
// non-nil UUID (the zero UUID would indicate a generation bug — this type
// must never be populated by uuid.New()/uuidv7(), only by parsing what ESI
// sent) and CorporationID must be a positive bigint identifier.
func (p CorporationProject) Validate() error {
	if p.ProjectID == uuid.Nil {
		return fmt.Errorf("domain: corporation_project.project_id must not be the nil UUID — it is CCP-supplied, never generated")
	}
	if p.CorporationID <= 0 {
		return fmt.Errorf("domain: corporation_project.corporation_id must be a positive bigint identifier, got %d", p.CorporationID)
	}
	return nil
}

// CorporationProjectContributor mirrors app.corporation_project_contributor.
type CorporationProjectContributor struct {
	ProjectID   uuid.UUID
	CharacterID int64
	JoinedAt    *time.Time
}

// CorporationProjectContribution mirrors app.corporation_project_contribution
// — the row joining a uuid PK against a bigint FK without coercion.
type CorporationProjectContribution struct {
	ProjectID   uuid.UUID
	CharacterID int64
	Amount      Money
}
