package domain_test

import (
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"

	"github.com/hangar-project/hangar/internal/domain"
)

// permissionRow mirrors one tuple from db/seed/permissions.sql's generated
// VALUES list.
type permissionRow struct {
	name, description, category string
}

// permissionTupleRE matches one ('name', 'description', 'category') tuple.
// db/seed/permissions.sql is itself generated by tools/gen-permission-seed
// from a fixed template (see main.go's sqlLit), so this pattern only needs
// to handle that one shape, including ” as the SQL escape for a literal
// single quote.
var permissionTupleRE = regexp.MustCompile(`\(\s*'((?:[^']|'')*)'\s*,\s*'((?:[^']|'')*)'\s*,\s*'((?:[^']|'')*)'\s*\)`)

// TestPermissionSeedMatchesGoSet is the CI divergence check the roadmap
// requires for app.permission: internal/domain.Permissions is the source of
// truth, db/seed/permissions.sql is generated from it
// (tools/gen-permission-seed), and this test fails the moment someone edits
// one without regenerating the other.
func TestPermissionSeedMatchesGoSet(t *testing.T) {
	seedPath := filepath.Join(moduleRoot(t), "db", "seed", "permissions.sql")
	raw, err := os.ReadFile(seedPath)
	if err != nil {
		t.Fatalf("reading %s: %v", seedPath, err)
	}

	matches := permissionTupleRE.FindAllStringSubmatch(string(raw), -1)
	if len(matches) == 0 {
		t.Fatalf("no permission tuples parsed out of %s — regex out of sync with the generator template?", seedPath)
	}

	seeded := make(map[string]permissionRow, len(matches))
	for _, m := range matches {
		row := permissionRow{
			name:        sqlUnescape(m[1]),
			description: sqlUnescape(m[2]),
			category:    sqlUnescape(m[3]),
		}
		seeded[row.name] = row
	}

	goSet := make(map[string]permissionRow, len(domain.Permissions))
	for _, p := range domain.Permissions {
		goSet[p.Name] = permissionRow{name: p.Name, description: p.Description, category: p.Category}
	}

	var missingFromSeed, extraInSeed, mismatched []string
	for name, want := range goSet {
		got, ok := seeded[name]
		switch {
		case !ok:
			missingFromSeed = append(missingFromSeed, name)
		case got != want:
			mismatched = append(mismatched, name)
		}
	}
	for name := range seeded {
		if _, ok := goSet[name]; !ok {
			extraInSeed = append(extraInSeed, name)
		}
	}

	sort.Strings(missingFromSeed)
	sort.Strings(extraInSeed)
	sort.Strings(mismatched)

	if len(missingFromSeed) > 0 {
		t.Errorf("in domain.Permissions but missing from db/seed/permissions.sql: %v — run `go generate ./internal/domain/...`", missingFromSeed)
	}
	if len(extraInSeed) > 0 {
		t.Errorf("in db/seed/permissions.sql but not in domain.Permissions: %v — the seed file was hand-edited", extraInSeed)
	}
	if len(mismatched) > 0 {
		t.Errorf("description/category differs between domain.Permissions and the seed file: %v", mismatched)
	}
}

func sqlUnescape(s string) string {
	return strings.ReplaceAll(s, "''", "'")
}
